[project]
name = "text2svg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cairosvg>=2.7.1",
    "numpy>=2.2.4",
    "torch>=2.6.0",
    "transformers>=4.50.3",
]
